language: ruby
bundler_args: --without development
branches:
  only:
    - master
    - stable
rvm:
  - 1.9.3
  - 1.9.2
  - jruby-19mode
  - jruby-head
  - rbx-19mode
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: jruby-19mode
  exclude:
    - rvm: 1.9.3
      jdk: openjdk7
    - rvm: 1.9.3
      jdk: openjdk6
    - rvm: 1.9.3
      jdk: oraclejdk7
    - rvm: 1.9.2
      jdk: openjdk7
    - rvm: 1.9.2
      jdk: openjdk6
    - rvm: 1.9.2
      jdk: oraclejdk7
    - rvm: rbx-19mode
      jdk: openjdk7
    - rvm: rbx-19mode
      jdk: openjdk6
    - rvm: rbx-19mode
      jdk: oraclejdk7
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
env:
  global:
    RAILS_ENV='test'
before_install:
  - gem update bundler
before_script:
  - bundle exec gem list
script: bundle exec rspec spec --profile
after_script: RAILS_ENV='production' gem build dtf.gemspec
notifications:
  irc:
    channels:
        - "irc.freenode.org#dtf-gems"
    on_failure: always
    on_success: always
  email:
    recipients:
      - me@daviddwdowney.com
    on_failure: always
    on_success: always
