rvm:
  - 1.9.3
before_script:
  - bundle exec thor dtf_setup:config
  - bundle exec rake db:migrate
  - bundle exec gem list
script: bundle exec rspec spec --format doc
language: ruby
notifications:
  irc:
    channels:
      - "irc.freenode.org#dtf-gems"
  email:
    recipients:
      - me@deryldoucette.com
    on_failure: change
