language: ruby
branches:
  only:
    - master
    - stable
rvm:
  - 1.9.3
  - 1.9.2
  - rbx-19mode
  - jruby-19mode
matrix:
  allow_failures:
    - rvm: 1.9.2
    - rvm: jruby-19mode
env:
  global:
    RAILS_ENV='test'
before_install:
  - gem update bundler
install:
  - bundle install --without development
before_script:
  - bundle exec gem list
script: bundle exec rspec spec --profile
after_script: RAILS_ENV='production' gem build dtf.gemspec
notifications:
  irc:
    channels:
        - "irc.freenode.org#dtf-gems"
    on_failure: always
    on_success: always
  email:
    recipients:
      - me@daviddwdowney.com
    on_failure: always
    on_success: always
