rvm:
  - 1.9.3
before_script:
  - thor dtf_setup:config
  - rake db:migrate
script: rspec spec --format doc
language: ruby
notifications:
  irc:
    channels:
      - "irc.freenode.org#dtf-gems"
  email:
    recipients:
      - me@deryldoucette.com
    on_failure: change
