language: ruby
rvm:
  - 1.9.3
  - rbx-19mode
before_install:
  - gem update bundler
before_script:
  - RAILS_ENV='development' bundle exec thor dtf_setup:config
  - RAILS_ENV='development' bundle exec rake db:migrate
  - RAILS_ENV='development' bundle exec gem list
script: RAILS_ENV='development' bundle exec rspec spec --format doc
notifications:
  irc:
    channels:
      - "irc.freenode.org#dtf-gems"
    on_success: always
    on_failure: always
  email:
    recipients:
      - me@daviddwdowney.com
    on_success: always
    on_failure: always
